### ISSUE TITLE
Build on Linux

### ISSUE THREAD

**Issue by shadowwalkersb** [GorgonCryoEM/Gorgon#16]

**Comment by shadowwalkersb** [comment]
Built on Linux (CentOS) successfully!

Need to fix OpenGL issues!

**Comment by shadowwalkersb** [comment]
Command:
/usr/bin/python gorgon.pyw &

Error output:

/usr/bin/python gorgon.pyw &

Xlib:  extension "GLX" missing on display ":1.0".
Xlib:  extension "GLX" missing on display ":1.0".
Xlib:  extension "GLX" missing on display ":1.0".
Xlib:  extension "GLX" missing on display ":1.0".
Xlib:  extension "GLX" missing on display ":1.0".
Xlib:  extension "GLX" missing on display ":1.0".
Xlib:  extension "GLX" missing on display ":1.0".
Xlib:  extension "GLX" missing on display ":1.0".
Xlib:  extension "GLX" missing on display ":1.0".
Xlib:  extension "GLX" missing on display ":1.0".
Xlib:  extension "GLX" missing on display ":1.0".
Xlib:  extension "GLX" missing on display ":1.0".
Xlib:  extension "GLX" missing on display ":1.0".
Xlib:  extension "GLX" missing on display ":1.0".
Xlib:  extension "GLX" missing on display ":1.0".
Xlib:  extension "GLX" missing on display ":1.0".
Xlib:  extension "GLX" missing on display ":1.0".
Xlib:  extension "GLX" missing on display ":1.0".
Xlib:  extension "GLX" missing on display ":1.0".
Xlib:  extension "GLX" missing on display ":1.0".
Xlib:  extension "GLX" missing on display ":1.0".
QGLContext::makeCurrent(): Cannot make invalid context current.
Xlib:  extension "GLX" missing on display ":1.0".
Xlib:  extension "GLX" missing on display ":1.0".
Traceback (most recent call last):
  File "/Gorgon/src_py/camera.py", line 565, in mousePressEvent
    self.processMouseDown(self.pickObject(self.mouseDownPoint.x(), self.mouseDownPoint.y()), event)  
  File "/Gorgon/src_py/camera.py", line 467, in pickObject
    glSelectBuffer(10000)
  File "/usr/lib/python2.6/site-packages/OpenGL/GL/pointers.py", line 238, in glSelectBuffer
    contextdata.setValue( simple.GL_SELECTION_BUFFER_POINTER, buffer )
  File "/usr/lib/python2.6/site-packages/OpenGL/contextdata.py", line 49, in setValue
    context = getContext( context )
  File "/usr/lib/python2.6/site-packages/OpenGL/contextdata.py", line 32, in getContext
    """Attempt to retrieve context when no valid context"""
OpenGL.error.Error: Attempt to retrieve context when no valid context
Traceback (most recent call last):
  File "/Gorgon/src_py/camera.py", line 574, in mouseReleaseEvent
    self.processMouseClick(self.pickObject(self.mouseUpPoint.x(), self.mouseUpPoint.y()), event, self.mouseLeftPressed, self.mouseMidPressed, self.mouseRightPressed)
  File "/Gorgon/src_py/camera.py", line 467, in pickObject
    glSelectBuffer(10000)
  File "/usr/lib/python2.6/site-packages/OpenGL/GL/pointers.py", line 238, in glSelectBuffer
    contextdata.setValue( simple.GL_SELECTION_BUFFER_POINTER, buffer )
  File "/usr/lib/python2.6/site-packages/OpenGL/contextdata.py", line 49, in setValue
    context = getContext( context )
  File "/usr/lib/python2.6/site-packages/OpenGL/contextdata.py", line 32, in getContext
    """Attempt to retrieve context when no valid context"""
OpenGL.error.Error: Attempt to retrieve context when no valid context

**Comment by shadowwalkersb** [comment]
The previous comment was a result from a vnc session. From the machine itself, however... here is a screenshot...
![screenshot](https://cloud.githubusercontent.com/assets/7955353/7094627/95891a14-df88-11e4-8b17-e7ba3895542e.png)

YAY!

**Comment by shadowwalkersb** [comment]
VNC session uses a driver other than Nvidia driver of the host machine, so it works on machine login , but not not on vnc login.

Closing this issue.

**Comment by taoju** [comment]
This is great!

Tao

On Wed, Apr 15, 2015 at 3:06 PM, shadowwalkersb notifications@github.com
wrote:

>  VNC session uses a driver other than Nvidia driver of the host machine,
> so it works on machine login , but not not on vnc login.
> 
> Closing this issue.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/GorgonCryoEM/Gorgon/issues/16#issuecomment-93550925.

## 

---

Tao Ju
Associate Professor, Department of Computer Science and Engineering
Ambassador, McDonnell International Scholar Academy
Washington University in St. Louis
One Brookings Drive, Campus Box 1045
Office: Jolley 406
Phone: 314-935-6648

## Web: http://www.cse.wustl.edu/~taoju

**Comment by shadowwalkersb** [comment]
Will close when packaging is complete.

**Comment by shadowwalkersb** [comment]
64 bit compiles
32 bit fails, will need more details (?)

/cc Wiki

**Comment by shadowwalkersb** [comment]
CentOS build notes:

1. yum groupinstall "Developer Tools"
1. yum install
1. install Python 2.7 from source
1. install pip
1. pyopengl
1. build Qt4
  1.  ```./configure -confirm-license -opensource -shared -fast -largefile -largefile -no-audio-backend -no-phonon -no-phonon-backend -no-webkit -no-javascript-jit -no-script -no-scripttools -no-xvideo -no-xsync -no-xinerama``` (see ./configure -help)
  1. gmake -j2
  1. sudo gmake install
1. build SIP
1. build PyQt4

Refs:
http://toomuchdata.com/2014/02/16/how-to-install-python-on-centos/
https://www.digitalocean.com/community/tutorials/how-to-set-up-python-2-7-6-and-3-3-3-on-centos-6-4
https://www.digitalocean.com/community/tutorials/how-to-set-up-python-2-7-6-and-3-3-3-on-centos-6-4

**Comment by shadowwalkersb** [comment]
**TO BE EDITED**
qt4 can be done with package manager
[patchelf](https://nixos.org/patchelf.html)
**Python setup**
pyenv
virtualenv
sip
pyqt4
pyopengl
pyinstaller
run post-pyinstaller.sh
```
patchelf --set-rpath    '$ORIGIN'       array.so                   
patchelf --set-rpath    '$ORIGIN'       binascii.so                
patchelf --set-rpath    '$ORIGIN'       _bisect.so                 
patchelf --set-rpath    '$ORIGIN'       bz2.so                     
patchelf --set-rpath    '$ORIGIN'       cmath.so                   
patchelf --set-rpath    '$ORIGIN'       _codecs_cn.so              
patchelf --set-rpath    '$ORIGIN'       _codecs_hk.so              
patchelf --set-rpath    '$ORIGIN'       _codecs_iso2022.so         
patchelf --set-rpath    '$ORIGIN'       _codecs_jp.so              
patchelf --set-rpath    '$ORIGIN'       _codecs_kr.so              
patchelf --set-rpath    '$ORIGIN'       _codecs_tw.so              
patchelf --set-rpath    '$ORIGIN'       _collections.so            
patchelf --set-rpath    '$ORIGIN'       cPickle.so                 
patchelf --set-rpath    '$ORIGIN'       cStringIO.so               
patchelf --set-rpath    '$ORIGIN'       _ctypes.so                 
patchelf --set-rpath    '$ORIGIN'       datetime.so                
patchelf --set-rpath    '$ORIGIN'       fcntl.so                   
patchelf --set-rpath    '$ORIGIN'       _functools.so              
patchelf --set-rpath    '$ORIGIN'       _hashlib.so                
patchelf --set-rpath    '$ORIGIN'       _heapq.so                  
patchelf --set-rpath    '$ORIGIN'       _io.so                     
patchelf --set-rpath    '$ORIGIN'       itertools.so               
patchelf --set-rpath    '$ORIGIN'       libpython2.7.so.1.0        
patchelf --set-rpath    '$ORIGIN'       _locale.so                 
patchelf --set-rpath    '$ORIGIN'       math.so                    
patchelf --set-rpath    '$ORIGIN'       _multibytecodec.so         
patchelf --set-rpath    '$ORIGIN'       operator.so                
patchelf --set-rpath    '$ORIGIN'       pyexpat.so                 
patchelf --set-rpath    '$ORIGIN'       _random.so                 
patchelf --set-rpath    '$ORIGIN'       readline.so                
patchelf --set-rpath    '$ORIGIN'       resource.so                
patchelf --set-rpath    '$ORIGIN'       select.so                  
patchelf --set-rpath    '$ORIGIN'       _socket.so                 
patchelf --set-rpath    '$ORIGIN'       _ssl.so                    
patchelf --set-rpath    '$ORIGIN'       strop.so                   
patchelf --set-rpath    '$ORIGIN'       _struct.so                 
patchelf --set-rpath    '$ORIGIN'       termios.so                 
patchelf --set-rpath    '$ORIGIN'       time.so                    
patchelf --set-rpath    '$ORIGIN'       unicodedata.so             
patchelf --set-rpath    '$ORIGIN'       zlib.so                    

rm libX11.so.6
rm libXext.so.6 libXfixes.so.3
rm libXinerama.so.1 libXr*
rm libXcursor.so.1
rm libXi.so.6
rm libXxf86vm.so.1
```

**Comment by shadowwalkersb** [comment]
Copied to https://github.com/GorgonCryoEM/Gorgon/wiki/CentOS-build-notes
