### ISSUE TITLE
External Libraries evaluation

### ISSUE THREAD

**Issue by shadowwalkersb** [GorgonCryoEM/Gorgon#19]
TODO:
- [x] Evaluation of the libraries that are needed and reduce the number of dependencies if possible
- [x] Clean up
  - [x] pkg-config files
  - [x] VS, ncb files
  - [x] lib files in alglib/
  - [x] Release/, Debug/

**Comment by shadowwalkersb** [comment]
@GorgonCryoEM/developers :
External Libraries are now in their own repository: [ExternalLibraries](/GorgonCryoEM/ExternalLibraries).

Question: Are the following libraries strictly independent from Gorgon? Are they maintained by others?

HelixSheetHunter
ImageSegmentation
schaefer_eigen

**Comment by taoju** [comment]
I don't know about the first two. The last one (schaefer_eigen) is most likely used for some numerical routines on eigenvector analysis, though I am not 100% sure that we can live without it... A search in the gorgon source code for the keyword might be helpful.

**Comment by FluffyDou** [comment]
HelixSheetHunter was written by Zeyun Yu from University of Texas at Austin. I have done a search in Gorgon and didn't see their reference in the cpp library project "Skeleton.sln". So far as I know, the only way for Python to interact with cpp program is through the library "libpyGORGON.pyd" built by that cpp library project. Thus I guess the current version of Gorgon is not using them. The same thing with ImageSegmentation.

We can try to remove the HelixSheetHunter and ImageSegmentation from External Library to see if the building still works.

**Comment by shadowwalkersb** [comment]
HelixSheetHunter seems to be a separate project. We can keep it in a utilities project. It would be nice to get an idea what this project can be used for. Similarly, if there are other useful projects under ExternalLibraries, it would be nice to know about. To decide if Gorgon depends on any of those, I will try to build Gorgon without them.

**Comment by FluffyDou** [comment]
That sounds great. I roughly checked out the Gorgon library project and it seems that very few libs in ExternalLibraries are used. I only saw FFTW and GL.

**Comment by shadowwalkersb** [comment]
The projects/folder under ExternalLibraries that are not needed for building Gorgon are now under a new repository, [Utilities](../../Utilities).

**Comment by shadowwalkersb** [comment]
External Libraries are cleaned up. Still working on CMakeLists and individual libraries that have binaries, #43 . Closing this issue.
