### ISSUE TITLE
Branch info needed: R1_0_2b-GraphMatchSheets-Branch

### ISSUE THREAD

**Issue by shadowwalkersb** [GorgonCryoEM/Gorgon#35]
@GorgonCryoEM/developers :

Does anyone know anything about this branch, [R1_0_2b-GraphMatchSheets-Branch](/GorgonCryoEM/Gorgon/tree/R1_0_2b-GraphMatchSheets-Branch)? Does it have anything important that needs to be incorporated to master? It seems to have diverged too much.

**Comment by taoju** [comment]
This is an implementation of a research prototype (extending the current
map-to-sequence helix matching to include sheets). I would like to keep
this branch in case we want to revisit, improve and publish.

Tao

On Sat, Apr 25, 2015 at 12:52 PM, shadowwalkersb notifications@github.com
wrote:

>  @GorgonCryoEM/developers
> https://github.com/orgs/GorgonCryoEM/teams/developers :
> 
> Does anyone know anything about this branch,
> R1_0_2b-GraphMatchSheets-Branch
> http:///GorgonCryoEM/Gorgon/tree/R1_0_2b-GraphMatchSheets-Branch? Does
> it have anything important that needs to be incorporated to master? It
> seems to have diverged too much.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/GorgonCryoEM/Gorgon/issues/35.

## 

---

Tao Ju
Associate Professor, Department of Computer Science and Engineering
Ambassador, McDonnell International Scholar Academy
Washington University in St. Louis
One Brookings Drive, Campus Box 1045
Office: Jolley 406
Phone: 314-935-6648

## Web: http://www.cse.wustl.edu/~taoju

**Comment by shadowwalkersb** [comment]
Any concerns about the branch being public?

**Comment by taoju** [comment]
No, although it has not been fully tested...

On Thu, Apr 30, 2015 at 9:52 AM, shadowwalkersb notifications@github.com
wrote:

>  Any concerns about the branch being public?
> 
> On Thu, Apr 30, 2015 at 12:40 AM, taoju notifications@github.com wrote:
> 
> > This is an implementation of a research prototype (extending the current
> > map-to-sequence helix matching to include sheets). I would like to keep
> > this branch in case we want to revisit, improve and publish.
> > 
> > Tao
> > 
> > On Sat, Apr 25, 2015 at 12:52 PM, shadowwalkersb <
> > notifications@github.com
> > 
> > > wrote:
> > > 
> > > @GorgonCryoEM/developers
> > > https://github.com/orgs/GorgonCryoEM/teams/developers :
> > > 
> > > Does anyone know anything about this branch,
> > > R1_0_2b-GraphMatchSheets-Branch
> > > http:///GorgonCryoEM/Gorgon/tree/R1_0_2b-GraphMatchSheets-Branch?
> > > Does
> > > it have anything important that needs to be incorporated to master? It
> > > seems to have diverged too much.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/GorgonCryoEM/Gorgon/issues/35.
> > 
> > ## 
> > 
> > ---
> > 
> > Tao Ju
> > Associate Professor, Department of Computer Science and Engineering
> > Ambassador, McDonnell International Scholar Academy
> > Washington University in St. Louis
> > One Brookings Drive, Campus Box 1045
> > Office: Jolley 406
> > Phone: 314-935-6648
> > 
> > ## Web: http://www.cse.wustl.edu/~taoju
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/GorgonCryoEM/Gorgon/issues/35#issuecomment-97667758
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/GorgonCryoEM/Gorgon/issues/35#issuecomment-97826916.

## 

---

Tao Ju
Associate Professor, Department of Computer Science and Engineering
Ambassador, McDonnell International Scholar Academy
Washington University in St. Louis
One Brookings Drive, Campus Box 1045
Office: Jolley 406
Phone: 314-935-6648

## Web: http://www.cse.wustl.edu/~taoju

**Comment by shadowwalkersb** [comment]
OK, no merging. Closing this issue.
