### ISSUE TITLE
Team and repo naming

### ISSUE THREAD

**Issue by shadowwalkersb** [GorgonCryoEM/Gorgon#8]
We need to decide on the team name and project name for Gorgon on **_BitBucket**_ and/or **_GitHub**_.

Currently, on both services, the team name is **gorgonCryoEM** and the repo name is **Gorgon** [gorgon (bitbucket.org)](https://bitbucket.org/gorgonCryoEM/gorgon) [Gorgon (github.com)](https://github.com/GorgonCryoEM/Gorgon)

**Comment by shadowwalkersb** [comment]
@mlbaker74 and @taoju : Any comments on this?

**Comment by taoju** [comment]
I am fine with the current names.

Thanks,
Tao

On Wed, Apr 15, 2015 at 3:07 PM, shadowwalkersb notifications@github.com
wrote:

>  @mlbaker74 https://github.com/mlbaker74 and @taoju
> https://github.com/taoju : Any comments on this?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/GorgonCryoEM/Gorgon/issues/8#issuecomment-93551133.

## 

---

Tao Ju
Associate Professor, Department of Computer Science and Engineering
Ambassador, McDonnell International Scholar Academy
Washington University in St. Louis
One Brookings Drive, Campus Box 1045
Office: Jolley 406
Phone: 314-935-6648

## Web: http://www.cse.wustl.edu/~taoju

**Comment by shadowwalkersb** [comment]
So if @mlbaker74 is OK, I am closing this issue and marking it as solved.
