### ISSUE TITLE
Evaluate using c++11 features and replacing legacy C with modern C++

### ISSUE THREAD

**Issue by shadowwalkersb** [GorgonCryoEM/Gorgon#90]
Switching may cause compilation errors. So, there will have to be more code fixing. Possible problems:
- [x] ~~[-Wc++11-narrowing] OpenGLUtils.h   /gitGorgonGithub/Foundation line 32~~ Turns out to be the only problem and is fixed
- [ ] char \* -> string
- [ ] comparison between NULL and non-pointer
- [ ] [-Wnull-conversion]

**Comment by shadowwalkersb** [comment]
A bigger problem may be that libraries like boost, fftw installed via MacPorts are linked against stdlib++ rather than libc++. This may be fixed by reinstalling all libraries and linking accordingly. However, **it is even a bigger problem when Gorgon is shipped with EMAN2**, if EMAN2 does not use -std=c++11 and -stdlib=libc++.

**Comment by sludtke42** [comment]
Are there C++11 features you need in Gorgon?  We try in EMAN to keep to older, more stable standards for better backwards compatibility.

---

Steven Ludtke, Ph.D.
Professor, Dept of Biochemistry and Mol. Biol.         (www.bcm.edu/biochem)
Co-Director National Center For Macromolecular Imaging        (ncmi.bcm.edu)
Co-Director CIBR Center                          (www.bcm.edu/research/cibr)
Baylor College of Medicine  
sludtke@bcm.edu

**Comment by shadowwalkersb** [comment]
Nothing too important to have right away. Just, maybe some conveniences that trigger my temptation from time to time. Like `auto` could get rid of type mismatches. I am concerned about a few of the compile warnings regarding `int` and `unsigned int` comparisons which may be causing infinite loops or unexpected termination conditions. But, they can be fixed manually.

**Comment by shadowwalkersb** [comment]
Oh, and `nullptr`. A lot of warnings I have are regarding `null-conversion`. I realize, fixing all those consistently may not be worth it, but since my job is "refactoring", I'd like to, at least, consider c++11. And for now I am just working with the existent code. I am sure I will be more than tempted if I have to write C++ code from scratch. C++11 feels more natural.

From [an article](http://blog.smartbear.com/c-plus-plus/the-biggest-changes-in-c11-and-why-you-should-care/):

> Bjarne Stroustrup, the creator of C++, said recently that C++11 “feels like a new language — the 
> pieces just fit together better.”

After writing the paragraph above, a quick Googling led me [here](http://www.codeproject.com/Articles/570638/Ten-Cplusplus-Features-Every-Cplusplus-Developer) and [here](http://herbsutter.com/elements-of-modern-c-style/). Both have `auto` and `nullptr` listed among the first three C++11 features.

**Comment by sludtke42** [comment]
Unfortunately c++11 doesn't feel 'natural' to the vast majority of programmers out there at this point, and with the potential compatibility issues i would like to strongly encourage you to stick with older standards unless it causes a critical problem...

**Comment by shadowwalkersb** [comment]
:+1: Copy that!
